---
- hosts: localhost
  connection: local
  pre_tasks:
    - name: set infrared facts
      set_fact:
        infrared_dir: "{{ lookup('env','WORKSPACE') }}/infrared"
        infrared_venv: "{{ lookup('env','WORKSPACE') }}/infrared/.venv/bin/activate"
      tags:
        - always
  roles:
    - { role: infrared-install, tags: [setup] }
    - { role: infrared-provision, tags: [setup] }
    - { role: infrared-undercloud, tags: [setup] }
    - { role: infrared-overcloud, tags: [setup] }
    - { role: infrared-cleanup, tags: [teardown] }
    
