---
- name: install undercloud
  command: > 
    cd {{ infrared_dir }} && source {{ infrared_venv }} &&  infrared tripleo-undercloud --version {{ version }} --images-task rpm --build {{ build }} 
    --config-options DEFAULT.local_ip={{ local_ip }} --config-options DEFAULT.network_gateway={{ network_gateway }} --config-options 
    DEFAULT.undercloud_public_vip={{ undercloud_public_vip }} --config-options DEFAULT.undercloud_admin_vip={{ undercloud_admin_vip }} --config-options 
    DEFAULT.network_cidr={{ network_cidr }} --config-options DEFAULT.masquerade_network={{ masquerade_network }} --config-options 
    DEFAULT.dhcp_start={{ dhcp_start }} --config-options  DEFAULT.dhcp_end={{ dhcp_end }} --config-options DEFAULT.inspection_iprange={{ inspection_iprange }}
